# Generated by Django 2.1.1 on 2018-09-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
